/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetolab;

/**
 *
 * @author dolva
 */

public class MenuPrincipal extends javax.swing.JFrame {

    posicaoJanelas centro = new posicaoJanelas();
   
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_via = new javax.swing.JMenu();
        via_cad = new javax.swing.JMenuItem();
        via_ed = new javax.swing.JMenuItem();
        Menu_moto = new javax.swing.JMenu();
        moto_cad = new javax.swing.JMenuItem();
        moto_ed = new javax.swing.JMenuItem();
        Menu_veic = new javax.swing.JMenu();
        veic_cad = new javax.swing.JMenuItem();
        veic_ed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Karrara Táxi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolab/karrara taxi.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 720));

        MenuPrincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, Short.MAX_VALUE)
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(MenuPrincipal);

        Menu_via.setText("Viagens");
        Menu_via.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_viaActionPerformed(evt);
            }
        });

        via_cad.setText("Cadastrar Viagem");
        via_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                via_cadActionPerformed(evt);
            }
        });
        Menu_via.add(via_cad);

        via_ed.setText("Editar Viagem");
        via_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                via_edActionPerformed(evt);
            }
        });
        Menu_via.add(via_ed);

        jMenuBar1.add(Menu_via);

        Menu_moto.setText("Motoristas");

        moto_cad.setText("Cadastrar Motorista");
        moto_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moto_cadActionPerformed(evt);
            }
        });
        Menu_moto.add(moto_cad);

        moto_ed.setText("Editar Motorista");
        moto_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moto_edActionPerformed(evt);
            }
        });
        Menu_moto.add(moto_ed);

        jMenuBar1.add(Menu_moto);

        Menu_veic.setText("Veículos");

        veic_cad.setText("Cadastrar Veículo");
        veic_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veic_cadActionPerformed(evt);
            }
        });
        Menu_veic.add(veic_cad);

        veic_ed.setText("Editar Veículo");
        veic_ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veic_edActionPerformed(evt);
            }
        });
        Menu_veic.add(veic_ed);

        jMenuBar1.add(Menu_veic);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("MenuPrincipal");
        getAccessibleContext().setAccessibleDescription("MenuPrincipal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Menu_viaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_viaActionPerformed
        
    }//GEN-LAST:event_Menu_viaActionPerformed

    private void via_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_via_edActionPerformed
        TabeladeItens obj4 = new TabeladeItens();
        centro.centralizar(obj4,MenuPrincipal);
        
    }//GEN-LAST:event_via_edActionPerformed

    private void via_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_via_cadActionPerformed
        CadastroViagem obj = new CadastroViagem();
        centro.centralizar(obj,MenuPrincipal);
    }//GEN-LAST:event_via_cadActionPerformed

    private void moto_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moto_cadActionPerformed
        CadastroMotorista obj2 =new CadastroMotorista();
        centro.centralizar(obj2,MenuPrincipal);
    }//GEN-LAST:event_moto_cadActionPerformed

    private void veic_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veic_cadActionPerformed
        CadastroVeiculo obj3 =new CadastroVeiculo();
        centro.centralizar(obj3,MenuPrincipal);
    }//GEN-LAST:event_veic_cadActionPerformed

    private void moto_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moto_edActionPerformed
        TabeladeItens obj4 = new TabeladeItens();
        obj4.selectTab_geral(1);
        centro.centralizar(obj4,MenuPrincipal);
    }//GEN-LAST:event_moto_edActionPerformed

    private void veic_edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veic_edActionPerformed
        TabeladeItens obj4 = new TabeladeItens();
        obj4.selectTab_geral(2);
        centro.centralizar(obj4,MenuPrincipal);
    }//GEN-LAST:event_veic_edActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MenuPrincipal;
    private javax.swing.JMenu Menu_moto;
    private javax.swing.JMenu Menu_veic;
    private javax.swing.JMenu Menu_via;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem moto_cad;
    private javax.swing.JMenuItem moto_ed;
    private javax.swing.JMenuItem veic_cad;
    private javax.swing.JMenuItem veic_ed;
    private javax.swing.JMenuItem via_cad;
    private javax.swing.JMenuItem via_ed;
    // End of variables declaration//GEN-END:variables

 
}
